<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WaterDaytimePreparationOverlay</AssemblyName>
    <RootNamespace>WaterDaytimePreparationOverlay</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../../daytime_preparation/src/water-icon.png"
                      LogicalName="WaterDaytimePreparationOverlay.WaterCurrency.png" />
  </ItemGroup>
</Project>
