return {
    -- Water 4.0 Integrated Preview v0.2.0. Broker and Contracts share one
    -- entrypoint, one Water mutation coordinator and one F6/F7 companion.
    runtime_mode = "unified_water4",
    water_trader_enabled = true,
    water4_shared_config_required = true,
    water_trader_purchase_enabled = true,
    water_trader_refresh_seconds = 7200,
    water_trader_poll_ms = 250,
    water_trader_hub_poll_ms = 1000,
    water_trader_input_poll_ms = 250,
    water_trader_input_lease_seconds = 6,
    -- Preserve v0.1.5's reviewed v0.1.3 state and rotation lineage.
    water_trader_state_path = false,
    water_trader_command_path = false,
    water_trader_input_path = false,
    water_trader_snapshot_path = false,
    water_trader_journal_path = false,
    water_trader_seed_namespace = "fw_water4_config_preview_013",
    water_trader_title = "WATER BROKER",

    unified_regular_vendor_scaling_enabled = true,
    unified_daytime_preparation_enabled = true,
    unified_overflow_guard_enabled = true,
    unified_hub_input_close_grace_seconds = 1,

    -- Contract configuration remains independent from Water4.ini.
    quest_runtime_enabled = true,
    quest_acceptance_required = true,
    acceptance_water_cost = 2,
    europan_kill_target = 5,
    water_barrel_target = 2,
    reward_currency_id = "framework_quest_test_token",
    reward_amount = 1,
    native_credit_reward_enabled = true,
    native_credit_reward_amount = 9500,
    native_xp_reward_enabled = true,
    native_xp_reward_amount = 1750,
    native_usp_reward_enabled = true,
    native_usp_reward_id = "PST01",
    native_usp_reward_amount = 1,
    native_power_cell_reward_enabled = false,
    native_power_cell_reward_id = "RareLoot_133_PowerCell",
    native_power_cell_reward_amount = 1,
    native_water_reward_enabled = false,
    native_water_reward_id = "WATER_oneDaySupply",
    native_water_reward_amount = 1,
    native_reward_delay_ms = 5000,
    quest_presentation_enabled = true,
    quest_presentation_path = false,
    quest_command_enabled = true,
    quest_command_path = false,
    quest_command_poll_ms = 250,
    -- Inert while runtime_mode=water_trader_mvp. Contract builds opt in to a
    -- session-bound external board state channel and a balanced local-player
    -- SetIgnoreLookInput/SetIgnoreMoveInput adapter.
    contract_board_input_enabled = true,
    contract_board_input_path = false,
    contract_board_input_poll_ms = 250,
    contract_board_input_lease_seconds = 6,
    overlay_auto_launch_enabled = true,
}
